import pygame
import time
import os


def welcomeMessage():
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/welcome.mp3")
    pygame.mixer.music.play(0)
    time.sleep(7)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/getReadyNight.mp3")
    pygame.mixer.music.play(0)
    time.sleep(8)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingRed.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("red"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(2)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingOrange.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("orange"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(2)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingWhite.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("white"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(2)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingGreen.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("green"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(2)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingYellow.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("yellow"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(2)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/pingingBlue.mp3")
    pygame.mixer.music.play(0)
    time.sleep(3)
    os.system("mosquitto_pub -h localhost -t test_channel -m " + str("test:") + str("blue"))
    time.sleep(3)
    pygame.mixer.music.load("/home/pi/Desktop/coreLightShow/effects/connected.mp3")
    pygame.mixer.music.play(0)
    time.sleep(5)